apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-quizdb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: https://github.com/Manohar-1305/quiz-website-portal.git
    targetRevision: main
    path: helm/mysql-quizdb
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
