apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quiz-app
  namespace: argocd
spec:
  project: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  source:
    repoURL: https://github.com/Manohar-1305/quiz-website-portal.git
    targetRevision: main
    path: helm/quiz-app
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

